name: Publish Mixam release of spring-velocity-support

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Package
        run: mvn clean package -DskipTests
      - name: Publish package
        run: mvn -B deploy:deploy-file -Durl=https://maven.pkg.github.com/mixam-platform/velocity-engine -DrepositoryId=github -Dfile=spring-velocity-support/target/spring-velocity-support-2.3-SNAPSHOT.jar -DgroupId=com.mixam.velocity -DartifactId=spring-velocity-support -Dversion=2.3-SNAPSHOT-${GITHUB_REF##*/} -DgeneratePom=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
